# Generated by Django 6.0.2 on 2026-02-28 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_eventmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_club',
            field=models.BooleanField(default=False, editable=False, verbose_name='Является ли кружком'),
        ),
    ]
