# Generated by Django 6.0.2 on 2026-02-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_event_is_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='is_club',
        ),
    ]
