# Generated by Django 6.0 on 2026-03-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_remove_event_is_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('organizer', 'Организатор'), ('parent', 'Родитель'), ('student', 'Учащийся')], default='student', max_length=63, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=63, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(max_length=63, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.CharField(max_length=63, verbose_name='Фамилия'),
        ),
    ]
