# Generated by Django 6.0 on 2026-03-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_customuser_role_alter_customuser_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('student', 'Учащийся'), ('parent', 'Родитель'), ('organizer', 'Организатор')], default='student', max_length=63, verbose_name='Роль'),
        ),
    ]
