# Generated by Django 6.0 on 2026-04-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0012_alter_event_organizer'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='specific_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата проведения'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='finish_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Время конца'),
        ),
    ]
